# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: wagnerstephan/bitbucket-git-ftp:latest
pipelines:
  custom:
    init:
    - step:
        caches:
          - node
        script:
          - git reset --hard
          - git ftp init  -u "$FTP_USERNAME" -p "$FTP_PASSWORD" ftp://$FTP_HOST
          - git ftp init -u "$FTP_USERNAME" -p "$FTP_PASSWORD" ftp://$FTP_HOST
    deploy:
    - step:
        caches:
          - node
        script:
          - git reset --hard
          - git ftp init  -u "$FTP_USERNAME" -p "$FTP_PASSWORD" ftp://$FTP_HOST
          - git ftp push -u "$FTP_USERNAME" -p "$FTP_PASSWORD" ftp://$FTP_HOST --all
  branches:
    master:
    - step:
        name: Deploy production
        deployment: production
        caches:
          - node
        script:
          - git reset --hard
          - git ftp init  -u "$FTP_USERNAME" -p "$FTP_PASSWORD" ftp://$FTP_HOST
          - git ftp push -u "$FTP_USERNAME" -p "$FTP_PASSWORD" ftp://$FTP_HOST